#!/bin/bash
pathBase="/home/usr/Monero"
pathMoneroBlockchain="${pathBase}/Blockchain/"
pathMoneroLog="${pathMoneroBlockchain}/monero.log"
pathMoneroNode="${pathBase}/monero-x86_64-linux-gnu-v0.17.3.2"
pathMoneroNodeBinary="${pathMoneroNode}/monerod"
pathScriptLog="${pathBase}/script.log"

chmod +x $pathMoneroNodeBinary

$pathMoneroNodeBinary \
  --data-dir $pathMoneroBlockchain \
  --log-file $pathMoneroLog \
  --log-level 0 \
  --max-log-file-size 0 \
  --p2p-bind-ip 0.0.0.0 \
  --p2p-bind-port 18080 \
  --rpc-restricted-bind-ip 0.0.0.0 \
  --rpc-restricted-bind-port 18089 \
  --db-sync-mode safe \
  --enable-dns-blocklist \
  --limit-rate-up 1048576 \
  --limit-rate-down 1048576 \
2>&1 | tee -a $pathScriptLog
